--USE [master]
--GO

/****** Object:  Database [eCommerce]    Script Date: 08/05/2022 13:53:46 ******/
CREATE DATABASE [eCommerce] ON  PRIMARY 
( NAME = N'eCommerce', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\eCommerce.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'eCommerce_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\eCommerce_log.ldf' , SIZE = 5184KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eCommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eCommerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eCommerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eCommerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eCommerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eCommerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [eCommerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eCommerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eCommerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eCommerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eCommerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eCommerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eCommerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eCommerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eCommerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eCommerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eCommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eCommerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eCommerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eCommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eCommerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eCommerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eCommerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eCommerce] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [eCommerce] SET  MULTI_USER 
GO

ALTER DATABASE [eCommerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eCommerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eCommerce] SET  READ_WRITE 
GO


